sudo: false
language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- pypy

# There are two accounts made specifically for Travis, and the passwords are really only encrypted for obscurity
# The global env variables `client1_email`, `client1_password`, `client2_email`, `client2_password` and `group_id` are set on the Travis Settings page

install:
  - pip install -U -r requirements.txt
  - pip install -U -r dev-requirements.txt

before_script:
  - if [[ "$TRAVIS_PYTHON_VERSION" = "2.7" ]]; then export PYTEST_ADDOPTS='-m ""'; fi; # expensive tests (otherwise disabled in pytest.ini)
  - if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then export PYTEST_ADDOPTS='-m offline'; fi; # offline tests only

script: python -m pytest || python -m pytest --lf; # Run failed tests twice

cache:
  pip: true
  directories:
    - .pytest_cache

deploy:
  provider: pypi
  user: madsmtm
  password:
    secure: "VA0MLSrwIW/T2KjMwjLZCzrLHw8pJT6tAvb48t7qpBdm8x192hax61pz1TaBZoJvlzyBPFKvluftuclTc7yEFwzXe7Gjqgd/ODKZl/wXDr36hQ7BBOLPZujdwmWLvTzMh3eJZlvkgcLCzrvK3j2oW8cM/+FZeVi/5/FhVuJ4ofs="
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    branch: master
    tags: true
